function test_results = test_basic_1_3_full()
%TEST_BASIC_1_3_FULL Run 288 rolling MILPs for multi-pump and P1-only.

test_root = fileparts(mfilename('fullpath'));
basic_root = fileparts(test_root);
addpath(basic_root, fullfile(basic_root,'controller'), ...
    fullfile(basic_root,'interfaces'), fullfile(basic_root,'scenarios'), ...
    fullfile(basic_root,'simulation'));
config = basic_mpc_config();
tol = 1e-7;

multi = simulate_basic_mpc(config, 'historical', 288, false, ...
    config.historical_start_day);
p1_config = config;
p1_config.pump_enabled = [true false false];
p1 = simulate_basic_mpc(p1_config, 'historical', 288, false, ...
    config.historical_start_day);

assert(isequal(multi.time,p1.time));
assert(isequal(multi.price_aud_per_mwh,p1.price_aud_per_mwh));
assert(isequal(multi.demand,p1.demand));
assert(multi.optimization_count == 288 && p1.optimization_count == 288);
assert(all(multi.optimization.horizon_steps == 288));
assert(all(p1.optimization.horizon_steps == 288));
assert(all(multi.exitflag > 0) && all(p1.exitflag > 0));
assert(multi.constraint_violations == 0 && p1.constraint_violations == 0);
assert(sum(multi.optimization.plan_level_violations) == 0);
assert(sum(p1.optimization.plan_level_violations) == 0);
assert(max(multi.optimization.plan_mass_balance_residual_m) < tol);
assert(max(p1.optimization.plan_mass_balance_residual_m) < tol);
assert(max(abs(multi.predicted_next_level_error_m)) < tol);
assert(max(abs(p1.predicted_next_level_error_m)) < tol);
assert(max(abs(multi.decision_tracking_error_m3s)) < tol);
assert(max(abs(multi.power_tracking_error_kw)) < tol);
assert(all(p1.pump_actual(:,2:3) == 0,'all'));
assert(isequal(multi.optimization.first_action,multi.pump_request));

test_results.multi = multi;
test_results.p1_only = p1;
fprintf(['FULL_MULTI_PASS optimizations=%d horizon=%d solve_total_s=%.6f ', ...
    'solve_mean_s=%.6f solve_max_s=%.6f exitflags=%s violations=%d ', ...
    'level=[%.6f,%.6f] final=%.6f volume_m3=%.3f cost=[%.6f,%.6f,%.6f] ', ...
    'switches=[%d,%d,%d] run_h=[%.6f,%.6f,%.6f]\n'], ...
    multi.optimization_count, config.horizon_steps, ...
    sum(multi.solve_time_seconds), mean(multi.solve_time_seconds), ...
    max(multi.solve_time_seconds), mat2str(unique(multi.exitflag)'), ...
    multi.constraint_violations, min(multi.level), max(multi.level), ...
    multi.final_level_m, multi.total_pumped_volume_m3, ...
    multi.total_energy_cost_aud, multi.total_switching_cost_aud, ...
    multi.total_cost_aud, multi.switch_count_by_pump, multi.pump_run_hours);
fprintf(['FULL_P1_PASS optimizations=%d horizon=%d solve_total_s=%.6f ', ...
    'solve_mean_s=%.6f solve_max_s=%.6f exitflags=%s violations=%d ', ...
    'level=[%.6f,%.6f] final=%.6f volume_m3=%.3f cost=[%.6f,%.6f,%.6f] ', ...
    'switches=[%d,%d,%d] run_h=[%.6f,%.6f,%.6f]\n'], ...
    p1.optimization_count, config.horizon_steps, ...
    sum(p1.solve_time_seconds), mean(p1.solve_time_seconds), ...
    max(p1.solve_time_seconds), mat2str(unique(p1.exitflag)'), ...
    p1.constraint_violations, min(p1.level), max(p1.level), ...
    p1.final_level_m, p1.total_pumped_volume_m3, ...
    p1.total_energy_cost_aud, p1.total_switching_cost_aud, ...
    p1.total_cost_aud, p1.switch_count_by_pump, p1.pump_run_hours);
end
