function figure_handle = plot_controller_comparison(comparison_results, output_file)
%PLOT_CONTROLLER_COMPARISON Plot Multi-pump and P1-only closed-loop results.
% Separate state lanes prevent identical binary schedules from hiding each
% other. Distinct line styles keep the figure readable in colour or print.

arguments
    comparison_results (1,1) struct
    output_file (1,:) char = ''
end

multi = comparison_results.multi;
p1 = comparison_results.p1_only;
config = multi.config;

figure_handle = figure('Name', 'Basic 1.3 Controller Comparison', ...
    'Color', 'white', 'Position', [60 20 1500 1180]);
layout = tiledlayout(5,1,'TileSpacing','compact','Padding','compact');
title(layout, sprintf(['Basic 1.3: Multi-pump MILP vs P1-only ', ...
    '(%d rolling optimizations)'], multi.optimization_count));

nexttile;
plot(multi.time, multi.price_aud_per_mwh, 'Color', [0.25 0.25 0.25], ...
    'LineWidth', 1.1);
ylabel('AUD/MWh');
title('Historical VIC1 price (perfect forecast input)');
grid on;

nexttile;
stairs(multi.time, 1000*multi.demand, '-', 'Color', [0.10 0.55 0.25], ...
    'LineWidth', 1.6);
ylabel('Demand L/s');
title('Richmond demand (same input for both controllers)');
grid on;

nexttile;
hold on;
lane_base = [3, 2, 1, 0];
lane_height = 0.70;
state_lines = gobjects(1,4);
state_lines(1) = stairs(multi.time, lane_base(1) + ...
    lane_height*multi.pump_actual(:,1), '-', ...
    'Color', [0.0000 0.4470 0.7410], 'LineWidth', 2.0);
state_lines(2) = stairs(multi.time, lane_base(2) + ...
    lane_height*multi.pump_actual(:,2), '--', ...
    'Color', [0.8500 0.3250 0.0980], 'LineWidth', 2.0);
state_lines(3) = stairs(multi.time, lane_base(3) + ...
    lane_height*multi.pump_actual(:,3), ':', ...
    'Color', [0.9290 0.6940 0.1250], 'LineWidth', 2.2);
state_lines(4) = stairs(p1.time, lane_base(4) + ...
    lane_height*p1.pump_actual(:,1), '-.', ...
    'Color', [0.10 0.10 0.10], 'LineWidth', 2.0);
hold off;
ylim([-0.15, 3.85]);
yticks(sort(lane_base + lane_height/2));
yticklabels({'P1-only (0/1)', 'Multi P3 (0/1)', ...
    'Multi P2 (0/1)', 'Multi P1 (0/1)'});
ylabel('Separate state lanes');
title('Actual pump states (0=off, 1=on)');
legend(state_lines, {'Multi P1: solid', 'Multi P2: dashed', ...
    'Multi P3: dotted', 'P1-only: dash-dot'}, 'Location', 'eastoutside');
grid on;

nexttile;
hold on;
multi_level = plot(multi.level_time, multi.level, '-', ...
    'Color', [0.0000 0.4470 0.7410], 'LineWidth', 2.0);
p1_level = plot(p1.level_time, p1.level, '--', ...
    'Color', [0.8500 0.3250 0.0980], 'LineWidth', 2.0);
lower_bound = yline(config.level_min_m, 'r:', 'Minimum level', ...
    'LineWidth', 1.2);
upper_bound = yline(config.level_max_m, 'r:', 'Maximum level', ...
    'LineWidth', 1.2);
hold off;
ylabel('Level m');
title(sprintf(['Tank level | final: Multi %.4f m, ', ...
    'P1-only %.4f m (different terminal inventories)'], ...
    multi.final_level_m, p1.final_level_m));
legend([multi_level, p1_level, lower_bound, upper_bound], ...
    {'Multi-pump: blue solid', 'P1-only: orange dashed', ...
     'Minimum bound', 'Maximum bound'}, 'Location', 'eastoutside');
grid on;

nexttile;
hold on;
multi_cost = plot(multi.time, multi.cumulative_total_cost_aud, '-', ...
    'Color', [0.0000 0.4470 0.7410], 'LineWidth', 2.0);
p1_cost = plot(p1.time, p1.cumulative_total_cost_aud, '--', ...
    'Color', [0.8500 0.3250 0.0980], 'LineWidth', 2.0);
hold off;
ylabel('Cost AUD');
xlabel('AEMO interval-ending time');
title(sprintf(['Cumulative cost | pumped volume: Multi %.0f m^3, ', ...
    'P1-only %.0f m^3'], multi.total_pumped_volume_m3, ...
    p1.total_pumped_volume_m3));
legend([multi_cost, p1_cost], ...
    {sprintf('Multi: %.4f AUD (%.5f AUD/m^3)', ...
        multi.total_cost_aud, ...
        multi.total_cost_aud/multi.total_pumped_volume_m3), ...
     sprintf('P1-only: %.4f AUD (%.5f AUD/m^3)', ...
        p1.total_cost_aud, ...
        p1.total_cost_aud/p1.total_pumped_volume_m3)}, ...
    'Location', 'eastoutside');
grid on;

if ~isempty(output_file)
    exportgraphics(figure_handle, output_file, 'Resolution', 180);
end
end
