%% RUN_BASIC_MPC Basic 1.1.1 historical-price economic MPC demonstration
clear; close all; clc;

basic_root = fileparts(mfilename('fullpath'));
addpath(basic_root);
addpath(fullfile(basic_root, 'controller'));
addpath(fullfile(basic_root, 'interfaces'));
addpath(fullfile(basic_root, 'scenarios'));
addpath(fullfile(basic_root, 'simulation'));

config = basic_mpc_config();
basic_results = simulate_basic_mpc(config, 'historical', ...
    config.default_simulation_steps, true);

fprintf('Basic 1.1.1 completed %d five-minute intervals.\n', ...
    numel(basic_results.u_actual));
fprintf('Data source: %s\n', basic_results.source_file);
fprintf('Tank-level range: %.3f to %.3f m; violations: %d.\n', ...
    min(basic_results.level), max(basic_results.level), ...
    basic_results.constraint_violations);
fprintf('Pump switches: %d; average paid RRP: %.2f AUD/MWh.\n', ...
    basic_results.switch_count, basic_results.average_price_when_on);
fprintf('Energy cost: %.2f AUD; total including switching: %.2f AUD.\n', ...
    basic_results.total_energy_cost_aud, basic_results.total_cost_aud);
fprintf(['Price-blind benchmark energy cost: %.2f AUD; total including ', ...
    'switching: %.2f AUD.\n'], ...
    basic_results.baseline.total_energy_cost_aud, ...
    basic_results.baseline.total_cost_aud);
