%% RUN_BASIC_MPC Basic 1.2 true rolling-horizon MPC demonstration
clear; close all; clc;

basic_root = fileparts(mfilename('fullpath'));
addpath(basic_root);
addpath(fullfile(basic_root, 'controller'));
addpath(fullfile(basic_root, 'interfaces'));
addpath(fullfile(basic_root, 'scenarios'));
addpath(fullfile(basic_root, 'simulation'));

config = basic_mpc_config();
basic_results = simulate_basic_mpc(config, 'historical', ...
    config.default_simulation_steps, true, config.historical_start_day);

output_file = fullfile(basic_root, ...
    'Basic_1_2_rolling_mpc_validation.png');
exportgraphics(gcf, output_file, 'Resolution', 200);

fprintf(['Basic 1.2 completed %d five-minute intervals with %d ', ...
    'separate optimizations.\n'], ...
    numel(basic_results.u_actual), basic_results.optimization_count);
fprintf('Every prediction horizon contained %d steps: %d.\n', ...
    config.horizon_steps, ...
    all(basic_results.optimization.horizon_steps == config.horizon_steps));
fprintf('Input samples: %d; last window: %d:%d.\n', ...
    basic_results.input_count, ...
    basic_results.optimization.window_start_index(end), ...
    basic_results.optimization.window_end_index(end));
fprintf('Displayed intervals: %s to %s.\n', ...
    string(basic_results.time(1)), string(basic_results.time(end)));
fprintf('Final prediction window: %s to %s.\n', ...
    string(basic_results.optimization.window_start_time(end)), ...
    string(basic_results.optimization.window_end_time(end)));
fprintf('Displayed-day negative-price intervals: %d.\n', ...
    nnz(basic_results.price_aud_per_mwh < 0));
fprintf('Full 575-point input negative-price intervals: %d.\n', ...
    nnz(basic_results.input_price_aud_per_mwh < 0));
fprintf('Data source: %s\n', basic_results.source_file);
fprintf('Tank-level range: %.3f to %.3f m; violations: %d.\n', ...
    min(basic_results.level), max(basic_results.level), ...
    basic_results.constraint_violations);
fprintf('Pump switches: %d; average paid RRP: %.2f AUD/MWh.\n', ...
    basic_results.switch_count, basic_results.average_price_when_on);
fprintf('Energy cost: %.2f AUD; total including switching: %.2f AUD.\n', ...
    basic_results.total_energy_cost_aud, basic_results.total_cost_aud);
fprintf(['Price-blind benchmark energy cost: %.2f AUD; total including ', ...
    'switching: %.2f AUD.\n'], ...
    basic_results.baseline.total_energy_cost_aud, ...
    basic_results.baseline.total_cost_aud);
fprintf('Saved rolling-MPC validation figure: %s\n', output_file);
