%% RUN_BASIC_MPC Basic 1.3 24-hour rolling three-pump MILP.
clear; close all; clc;
basic_root = fileparts(mfilename('fullpath'));
addpath(basic_root, fullfile(basic_root,'controller'), ...
    fullfile(basic_root,'interfaces'), fullfile(basic_root,'scenarios'), ...
    fullfile(basic_root,'simulation'));
config = basic_mpc_config();
basic_results = simulate_basic_mpc(config, 'historical', ...
    config.default_simulation_steps, false, config.historical_start_day);
plot_file = fullfile(basic_root, 'Basic_1_3_multi_pump_closed_loop.png');
plot_basic_mpc_results(basic_results, plot_file);
fprintf(['Basic 1.3: %d rolling MILPs, horizon=%d, level=%.4f-%.4f m, ', ...
    'violations=%d, total cost=%.4f AUD, solve time=%.3f s.\n'], ...
    basic_results.optimization_count, config.horizon_steps, ...
    min(basic_results.level), max(basic_results.level), ...
    basic_results.constraint_violations, basic_results.total_cost_aud, ...
    sum(basic_results.solve_time_seconds));
